### PR TITLE
Added Traditional Chinese

### PR DESCRIPTION
**Pull request by shps951023**
Added Traditional Chinese

### CODE REVIEW

**Comment by findersky** [comment]
> Added Traditional Chinese

Startup.cs must be update .

**Comment by findersky** [comment]
> Added Traditional Chinese
@shps951023 

"Startup.cs" must be update .

**Comment by shps951023** [comment]
> > Added Traditional Chinese
> > @shps951023
> 
> "Startup.cs" must be update .

thanks,I fix it.

**Review by shps951023 — COMMENTED** [review]
add CultureInfo("zh-tw")

**Pull request merged**
