### PR TITLE
reconstruction

### PR DESCRIPTION
**Pull request by dorthl**
It seems that the project has not been maintained for a long time
I recently tried using the software and modified it extensively
I'm very interested in this project and hope to continue to maintain it
The changes are still in progress. If you don't have time to manage it, I hope you can add me as a collaborator or transfer the project
[Note] These changes are destructive changes I rewrote it

### CODE REVIEW

**Comment by dorthl** [comment]
@rxtur

**Comment by dorthl** [comment]
@farzindev

**Comment by farzindev** [comment]
Hey @dorthl  I just sent you an email. I'm interested in upgrading Blogifier. Let's talk.

**Comment by dorthl** [comment]
@farzindev I answered the email

**Comment by rxtur** [comment]
Added you as a collaborator to the project. Just please remember this adds you responsibility to maintain code, specially react to security issues that often sneak in with new code.

**Comment by dorthl** [comment]
@rxtur @farzindev 
Thanks if you guys have no comments I will start the active merge
I'll close this merge request. I've checked my commits and there are some issues. I'll do a new squeeze merge. If you guys don't mind I'll start working on it tomorrow.
I will merge into the dev branch and then merge into the main branch when the test is complete.

**Pull request closed without merging**
