### PR TITLE
add Persian Resources

### PR DESCRIPTION
**Pull request by amira133**

### CODE REVIEW

**Comment by rxtur** [comment]
Why there so many updates in the request? I would expect single changed file here, not 27.

**Comment by farzindev** [comment]
@rxtur I think he merged the dev with main and then did the pull request.
now, I merged the dev with the main myself and now it's a one file pull request.

**Comment by rxtur** [comment]
> @rxtur I think he merged the dev with main and then did the pull request.
> now, I merged the dev with the main myself and now it's a one file pull request.

Got it, thanks. I merged pull request itself.

**Comment by amira133** [comment]
@rxtur,@farzindev I'm sorry, I think I should have changed the branch and then asked for a pull request.

**Pull request merged**
